import Head from "next/head";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import "@/styles/globals.css";
import {useState} from 'react'

export default function App({ Component, pageProps }) {
  const [showSidebar,setShowSidebar] = useState(false)
  return (
    <>
      <Head>
        <title>Spotify - Reproductor Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-spotify-black min-h-screen text-gray-300">
        <Header setShowSidebar={setShowSidebar}/>
        <Sidebar showSidebar={showSidebar} setShowSidebar={setShowSidebar}/>
        <main>
          <Component {...pageProps} />
        </main>
      </div>
    </>
  );
}
